### ISSUE TITLE
Snes config

### ISSUE THREAD

**Issue by ghost** [HattDroid/Retroarch-Settings-for-Fidelity#1]
Can u plz share bezels/SNES/default.cfg for SNES? it mentions on config but does not exist in my Onion OS

**Comment by HattDroid** [comment]
Just booted my Mini Plus with the latest update and it's here on my side.

Else, I just looked up onionos repo and it seems that it's the "default" configuration present here:
https://github.com/OnionUI/Onion/tree/main/static/build/RetroArch/.retroarch/overlay/4-3/Frames

Maybe they very recently changed the path of the overlay and somehow it didn't update on my console.

**Comment by HattDroid** [comment]
It is confirmed that they deleted this path. The line logging the change is here:
https://github.com/OnionUI/Onion/blob/2fab2caf9937d7a7558a65e6a992d7baaac0f2ca/static/build/.tmp_update/script/migration/data/overlay_filter_changes.tsv#L393C1-L393C34

I guess we will have to compose with the new folder organisation. For info, all onionos overlays are here:
https://github.com/OnionUI/Onion/tree/main/static/build/RetroArch/.retroarch/overlay
